// <auto-generated />
using System;
using IntranetPortal.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IntranetPortal.Infrastructure.Migrations
{
    [DbContext(typeof(IntranetDbContext))]
    [Migration("20251126214725_FixDateTimeHandling")]
    partial class FixDateTimeHandling
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IntranetPortal.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("LogID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Action");

                    b.Property<int?>("BirimID")
                        .HasColumnType("integer")
                        .HasColumnName("BirimID");

                    b.Property<int?>("BirimID1")
                        .HasColumnType("integer");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("Details");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("IPAddress");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Resource");

                    b.Property<DateTime>("TarihSaat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("TarihSaat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("UserID")
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    b.Property<int?>("UserID1")
                        .HasColumnType("integer");

                    b.HasKey("LogID");

                    b.HasIndex("Action")
                        .HasDatabaseName("idx_auditlog_action");

                    b.HasIndex("BirimID")
                        .HasDatabaseName("idx_auditlog_birim");

                    b.HasIndex("BirimID1");

                    b.HasIndex("TarihSaat")
                        .HasDatabaseName("idx_auditlog_tarih");

                    b.HasIndex("UserID")
                        .HasDatabaseName("idx_auditlog_user");

                    b.HasIndex("UserID1");

                    b.HasIndex("UserID", "TarihSaat")
                        .HasDatabaseName("idx_auditlog_user_tarih");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Domain.Entities.Birim", b =>
                {
                    b.Property<int>("BirimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("BirimID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BirimID"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Aciklama");

                    b.Property<string>("BirimAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("BirimAdi");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("BirimID");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_birim_active");

                    b.ToTable("Birim", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PermissionID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Action");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Description");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Resource");

                    b.HasKey("PermissionID");

                    b.HasIndex("Action", "Resource")
                        .IsUnique()
                        .HasDatabaseName("idx_permission_action_resource");

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RoleID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Aciklama");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RoleAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("RoleAdi");

                    b.HasKey("RoleID");

                    b.HasIndex("RoleAdi")
                        .IsUnique()
                        .HasDatabaseName("idx_role_adi");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("GrantedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("GrantedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PermissionID")
                        .HasColumnType("integer")
                        .HasColumnName("PermissionID");

                    b.Property<int?>("PermissionID1")
                        .HasColumnType("integer");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer")
                        .HasColumnName("RoleID");

                    b.HasKey("ID");

                    b.HasIndex("PermissionID")
                        .HasDatabaseName("idx_roleperm_permission");

                    b.HasIndex("PermissionID1");

                    b.HasIndex("RoleID")
                        .HasDatabaseName("idx_roleperm_role");

                    b.HasIndex("RoleID", "PermissionID")
                        .IsUnique()
                        .HasDatabaseName("idx_roleperm_role_permission");

                    b.ToTable("RolePermission", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Domain.Entities.SystemSettings", b =>
                {
                    b.Property<int>("SettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("SettingID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SettingID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Description");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("SettingKey");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("SettingValue");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("integer")
                        .HasColumnName("UpdatedByUserID");

                    b.HasKey("SettingID");

                    b.HasIndex("SettingKey")
                        .IsUnique()
                        .HasDatabaseName("idx_systemsettings_key");

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Domain.Entities.UploadedFile", b =>
                {
                    b.Property<Guid>("FileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("FileID");

                    b.Property<int>("BirimID")
                        .HasColumnType("integer")
                        .HasColumnName("BirimID");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<int>("EntityID")
                        .HasColumnType("integer")
                        .HasColumnName("EntityID");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("EntityType");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("FileExtension");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("FileHash");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("FileName");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("FilePath");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("FileSize");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("MimeType");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("OriginalFileName");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("UploadedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UploadedByUserID")
                        .HasColumnType("integer")
                        .HasColumnName("UploadedByUserID");

                    b.Property<int?>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("FileID");

                    b.HasIndex("BirimID");

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("idx_uploadedfile_date");

                    b.HasIndex("UploadedByUserID")
                        .HasDatabaseName("idx_uploadedfile_user");

                    b.HasIndex("UserID");

                    b.HasIndex("EntityType", "EntityID")
                        .HasDatabaseName("idx_uploadedfile_entity");

                    b.ToTable("UploadedFile", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("AdSoyad");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("SifreHash");

                    b.Property<DateTime?>("SonGiris")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("SonGiris");

                    b.Property<string>("Unvan")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Unvan");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_user_email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_user_active");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Domain.Entities.UserBirimRole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("AssignedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("BirimID")
                        .HasColumnType("integer")
                        .HasColumnName("BirimID");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer")
                        .HasColumnName("RoleID");

                    b.Property<int?>("RoleID1")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    b.HasKey("ID");

                    b.HasIndex("BirimID")
                        .HasDatabaseName("idx_userbr_birim");

                    b.HasIndex("RoleID")
                        .HasDatabaseName("idx_userbr_role");

                    b.HasIndex("RoleID1");

                    b.HasIndex("UserID")
                        .HasDatabaseName("idx_userbr_user");

                    b.HasIndex("UserID", "BirimID")
                        .IsUnique()
                        .HasDatabaseName("idx_userbr_user_birim");

                    b.ToTable("UserBirimRole", (string)null);
                });

            modelBuilder.Entity("IntranetPortal.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("IntranetPortal.Domain.Entities.Birim", "Birim")
                        .WithMany()
                        .HasForeignKey("BirimID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_auditlog_birim");

                    b.HasOne("IntranetPortal.Domain.Entities.Birim", null)
                        .WithMany("AuditLogs")
                        .HasForeignKey("BirimID1");

                    b.HasOne("IntranetPortal.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_auditlog_user");

                    b.HasOne("IntranetPortal.Domain.Entities.User", null)
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserID1");

                    b.Navigation("Birim");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntranetPortal.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("IntranetPortal.Domain.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roleperm_permission");

                    b.HasOne("IntranetPortal.Domain.Entities.Permission", null)
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionID1");

                    b.HasOne("IntranetPortal.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roleperm_role");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IntranetPortal.Domain.Entities.SystemSettings", b =>
                {
                    b.HasOne("IntranetPortal.Domain.Entities.User", "UpdatedByUser")
                        .WithMany("SystemSettings")
                        .HasForeignKey("UpdatedByUserID");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("IntranetPortal.Domain.Entities.UploadedFile", b =>
                {
                    b.HasOne("IntranetPortal.Domain.Entities.Birim", "Birim")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("BirimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntranetPortal.Domain.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_uploadedfile_user");

                    b.HasOne("IntranetPortal.Domain.Entities.User", null)
                        .WithMany("UploadedFiles")
                        .HasForeignKey("UserID");

                    b.Navigation("Birim");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("IntranetPortal.Domain.Entities.UserBirimRole", b =>
                {
                    b.HasOne("IntranetPortal.Domain.Entities.Birim", "Birim")
                        .WithMany("UserBirimRoles")
                        .HasForeignKey("BirimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_userbr_birim");

                    b.HasOne("IntranetPortal.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_userbr_role");

                    b.HasOne("IntranetPortal.Domain.Entities.Role", null)
                        .WithMany("UserBirimRoles")
                        .HasForeignKey("RoleID1");

                    b.HasOne("IntranetPortal.Domain.Entities.User", "User")
                        .WithMany("UserBirimRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_userbr_user");

                    b.Navigation("Birim");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntranetPortal.Domain.Entities.Birim", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("UploadedFiles");

                    b.Navigation("UserBirimRoles");
                });

            modelBuilder.Entity("IntranetPortal.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("IntranetPortal.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserBirimRoles");
                });

            modelBuilder.Entity("IntranetPortal.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("SystemSettings");

                    b.Navigation("UploadedFiles");

                    b.Navigation("UserBirimRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
